periodics:
- name: ci-kubernetes-e2e-gke-device-plugin-gpu
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-beta
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/k8s-beta
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-monitoring
  interval: 3h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=1
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:StackdriverAcceleratorMonitoring\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-p100
  interval: 12h #expensive test
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-p100,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-p100-beta
  interval: 12h #expensive test
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/k8s-beta
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-p100,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-p100-stable1
  interval: 12h #expensive test
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/k8s-stable1
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-p100,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-p100-stable2
  interval: 12h #expensive test
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/k8s-stable2
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-p100,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-stable1
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/k8s-stable1
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-stable2
  interval: 12h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/k8s-stable2
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- name: ci-kubernetes-e2e-gke-device-plugin-gpu-ubuntu
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=300
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --env=NVIDIA_DRIVER_INSTALLER_DAEMONSET=https://raw.githubusercontent.com/GoogleCloudPlatform/container-engine-accelerators/master/nvidia-driver-installer/ubuntu/daemonset.yaml
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=ubuntu
      - --gcp-project-type=gpu-project
      - --gcp-zone=us-west1-b
      - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
