presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-device-plugin-gpu
    skip_branches:
    - release-1.10  # per-release image
    - release-1.9  # per-release image
    always_run: true
    skip_report: false
    max_concurrency: 12
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/pull-kubernetes-e2e.env
        - --env-file=jobs/env/pull-kubernetes-e2e-gce-device-plugin-gpu.env
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-nodes=4
        - --gcp-project=k8s-jkns-pr-gce-gpus
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-device-plugin-gpu
        - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
        - --timeout=60m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gce-device-plugin-gpu
    branches:
    - release-1.10  # per-release image
    always_run: true
    skip_report: false
    max_concurrency: 12
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.10
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/pull-kubernetes-e2e.env
        - --env-file=jobs/env/pull-kubernetes-e2e-gce-device-plugin-gpu.env
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-nodes=4
        - --gcp-project=k8s-jkns-pr-gce-gpus
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-device-plugin-gpu
        - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
        - --timeout=60m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gce-device-plugin-gpu
    branches:
    - release-1.9 # per-release image
    always_run: true
    skip_report: false
    max_concurrency: 12
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.9
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/pull-kubernetes-e2e.env
        - --env-file=jobs/env/pull-kubernetes-e2e-gce-device-plugin-gpu.env
        - --extract=local
        - --gcp-node-image=gci
        - --gcp-nodes=4
        - --gcp-project=k8s-jkns-pr-gce-gpus
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-device-plugin-gpu
        - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
        - --timeout=60m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gke-device-plugin-gpu
    skip_branches:
    - release-1.10  # per-release image
    - release-1.9  # per-release image
    always_run: false
    skip_report: false
    max_concurrency: 1
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --deployment=gke
        - --extract=local
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-project=k8s-gke-gpu-pr
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
        - --gke-environment=test
        - --provider=gke
        - --stage=gs://kubernetes-release-dev/ci
        - --stage-suffix=pull-kubernetes-e2e-gke-device-plugin-gpu
        - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
        - --timeout=60m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gke-device-plugin-gpu
    branches:
    - release-1.10  # per-release image
    always_run: false
    skip_report: false
    max_concurrency: 1
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.10
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --deployment=gke
        - --extract=local
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-project=k8s-gke-gpu-pr
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
        - --gke-environment=test
        - --provider=gke
        - --stage=gs://kubernetes-release-dev/ci
        - --stage-suffix=pull-kubernetes-e2e-gke-device-plugin-gpu
        - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
        - --timeout=60m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gke-device-plugin-gpu
    branches:
    - release-1.9  # per-release image
    always_run: false
    skip_report: false
    max_concurrency: 1
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.9
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=90"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --deployment=gke
        - --extract=local
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-project=k8s-gke-gpu-pr
        - --gcp-zone=us-west1-b
        - --ginkgo-parallel=30
        - --gke-create-command=container clusters create --accelerator=type=nvidia-tesla-k80,count=2
        - --gke-environment=test
        - --provider=gke
        - --stage=gs://kubernetes-release-dev/ci
        - --stage-suffix=pull-kubernetes-e2e-gke-device-plugin-gpu
        - --test_args=--ginkgo.focus=\[Feature:GPUDevicePlugin\] --minStartupPods=8
        - --timeout=60m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
