periodics:
- name: ci-docker-node-conformance
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20180827-b09cde7d7-master
      args:
      - --repo=k8s.io/kubernetes=master
      - --timeout=90
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --deployment=node
      - --gcp-zone=us-central1-f
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml
      - --node-test-args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Serial\]"
      - --timeout=65m
      env:
      - name: GOPATH
        value: /go

- name: ci-docker-node-features
  interval: 4h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20180827-b09cde7d7-master
      args:
      - --repo=k8s.io/kubernetes=master
      - --timeout=200
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --deployment=node
      - --gcp-zone=us-central1-f
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml
      - --node-test-args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=8 --focus="\[NodeFeature:.+\]" --skip="\[Flaky\]|\[Serial\]"
      - --timeout=180m
      env:
      - name: GOPATH
        value: /go

- name: ci-docker-node-legacy
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20180827-b09cde7d7-master
      args:
      - --repo=k8s.io/kubernetes=master
      - --timeout=200
      - --root=/go/src
      - --
      - --deployment=node
      - --gcp-zone=us-central1-f
      - --node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/image-config.yaml
      - --node-test-args=--kubelet-flags="--cgroups-per-qos=true --cgroup-root=/"
      - --node-tests=true
      - --provider=gce
      - --test_args=--nodes=1 --focus="\[Legacy:Docker\]" --skip="\[Flaky\]"
      - --timeout=180m
      env:
      - name: GOPATH
        value: /go
