# this config file contains all config fields with comments
apiVersion: kind.sigs.k8s.io/v1alpha1
kind: Config
# number of nodes in the cluster (currently only 1 is supported)
numNodes: 1
# template for kubeadm config, "" -> the default template
kubeadmConfigTemplate: ""
# node lifecycle hooks
nodeLifecycle:
  # commands run before systemd boots
  preBoot:
  - name: "should fail"
    command: [ "yep-not-a-real-command" ]
  # commands run before kubeadm init
  preKubeadm: []
  # commands run after kubeadm init
  postKubeadm: []
  # commands run after all other setup on the node
  postSetup:
  - name: "list containers"
    command: [ "docker", "ps" ]
    # this command cannot fail, or else kind will fail during create
    mustSucceed: true
