periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-prod
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=620
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-b
      - --gke-environment=prod
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Slow\]|\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=600m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-prod-parallel
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=100
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-b
      - --ginkgo-parallel
      - --gke-environment=prod
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-prod-smoke
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=100
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --check-version-skew=false
      - --cluster=
      - --deployment=gke
      - --extract=gke
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/rc
      - --gcp-node-image=gci
      - --gcp-zone=us-east1-d
      - --ginkgo-parallel
      - --gke-environment=prod
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=80m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
