# kubeadm network tests
periodics:
- name: ci-kubernetes-e2e-kubeadm-gce-cni-flannel
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=ci/latest-bazel
      - --gcp-zone=us-central1-f
      - --kubeadm=ci
      - --kubernetes-anywhere-cni=flannel
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel
      - --kubernetes-anywhere-kubernetes-version=ci-cross/latest
      - --provider=kubernetes-anywhere
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m

- name: ci-kubernetes-e2e-kubeadm-gce-dns-coredns
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=ci/latest-bazel
      - --gcp-zone=us-central1-f
      - --kubeadm=ci
      - --kubernetes-anywhere-kubeadm-feature-gates=CoreDNS=true
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel
      - --kubernetes-anywhere-kubernetes-version=ci-cross/latest
      - --provider=kubernetes-anywhere
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m

- name: ci-kubernetes-e2e-kubeadm-gce-ipvs
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=ci/latest-bazel
      - --gcp-zone=us-central1-f
      - --kubeadm=ci
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel
      - --kubernetes-anywhere-kubernetes-version=ci-cross/latest
      - --kubernetes-anywhere-proxy-mode=ipvs
      - --provider=kubernetes-anywhere
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m
