# kubeadm upgrade tests
periodics:
- name: ci-kubernetes-e2e-kubeadm-gce-upgrade-1-9-1-10
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=release-1.10
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-version-skew=false
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=release/latest-1.10
      - --extract=ci/latest-bazel-1.9
      - --gcp-zone=us-central1-f
      - --kubeadm=periodic
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel-1.9
      - --kubernetes-anywhere-kubernetes-version=ci/latest-1.9
      - --kubernetes-anywhere-upgrade-method=upgrade
      - --provider=kubernetes-anywhere
      - --skew
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\]
      - --timeout=300m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --ginkgo.skip=statefulset-upgrade|hpa-upgrade|service-upgrade --upgrade-target=release/latest-1.10

- name: ci-kubernetes-e2e-kubeadm-gce-upgrade-1-10-1-11
  interval: 2h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=release-1.11
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-version-skew=false
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=release/latest-1.11
      - --extract=ci/latest-bazel-1.10
      - --gcp-zone=us-central1-f
      - --kubeadm=periodic
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel-1.10
      - --kubernetes-anywhere-kubernetes-version=ci/latest-1.10
      - --kubernetes-anywhere-upgrade-method=upgrade
      - --provider=kubernetes-anywhere
      - --skew
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --ginkgo.skip=statefulset-upgrade|hpa-upgrade|service-upgrade --upgrade-target=release/latest-1.11

- name: ci-kubernetes-e2e-kubeadm-gce-upgrade-1-11-1-12
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=release-1.12
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-version-skew=false
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=release/latest-1.12
      - --extract=ci/latest-bazel-1.11
      - --gcp-zone=us-central1-f
      - --kubeadm=periodic
      - --kubernetes-anywhere-kubelet-ci-version=latest-bazel-1.11
      - --kubernetes-anywhere-kubernetes-version=ci/latest-1.11
      - --kubernetes-anywhere-upgrade-method=upgrade
      - --provider=kubernetes-anywhere
      - --skew
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --ginkgo.skip=statefulset-upgrade|hpa-upgrade|service-upgrade --upgrade-target=release/latest-1.9

- name: ci-kubernetes-e2e-kubeadm-gce-upgrade-stable-master
  interval: 6h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/e2e-kubeadm:v20180829-29d5569b7
      args:
      - --repo=k8s.io/kubernetes=master
      - --repo=k8s.io/kubernetes-anywhere=kubeadm-e2e
      - --timeout=320
      - --upload=gs://kubernetes-jenkins/logs
      - --scenario=kubernetes_e2e
      - --
      - --check-version-skew=false
      - --cluster=
      - --deployment=kubernetes-anywhere
      - --extract=ci/latest
      - --extract=release/stable
      - --gcp-zone=us-central1-f
      - --kubeadm=periodic
      - --kubernetes-anywhere-kubelet-version=stable
      - --kubernetes-anywhere-kubernetes-version=stable
      - --kubernetes-anywhere-upgrade-method=upgrade
      - --provider=kubernetes-anywhere
      - --skew
      - --test_args=--ginkgo.focus=\[Conformance\]|\[Feature:BootstrapTokens\]|\[Feature:NodeAuthorizer\] --minStartupPods=8
      - --timeout=300m
      - --upgrade_args=--ginkgo.focus=\[Feature:MasterUpgrade\] --ginkgo.skip=statefulset-upgrade|hpa-upgrade|service-upgrade --upgrade-target=ci-cross/latest
