# package tests
periodics:
- name: periodic-kubernetes-e2e-packages-pushed
  interval: 24h
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=60
      - --repo=k8s.io/kubeadm=master
      - --scenario=execute
      - --
      - ./tests/e2e/verify_packages_published.sh
      image: gcr.io/k8s-testimages/kubekins-e2e:latest-master
      imagePullPolicy: Always
