presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gce-100-performance
    always_run: true
    skip_report: false
    max_concurrency: 12
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=120
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/ci-kubernetes-e2e-scalability-common.env
        - --env-file=jobs/env/ci-kubernetes-e2e-gci-gce-scalability.env
        - --extract=local
        - --gcp-nodes=100
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-100-performance
        - --tear-down-previous
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --minStartupPods=8 --gather-resource-usage=true --gather-metrics-at-teardown=true
        - --timeout=100m
        - --use-logexporter
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-e2e-gce-big-performance
    always_run: false
    max_concurrency: 1
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=270
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env=HEAPSTER_MACHINE_TYPE=n1-standard-4
        - --env-file=jobs/env/ci-kubernetes-e2e-scalability-common.env
        - --env-file=jobs/env/ci-kubernetes-e2e-scalability-highspeed-common.env
        - --extract=local
        - --gcp-nodes=500
        - --gcp-project=k8s-scale-testing
        - --gcp-zone=us-east1-a
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-big-performance
        - --tear-down-previous
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --minStartupPods=8 --gather-resource-usage=master --gather-metrics-at-teardown=master
        - --timeout=240m
        - --use-logexporter
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-e2e-gce-large-performance
    always_run: false
    max_concurrency: 1
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=570
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env=HEAPSTER_MACHINE_TYPE=n1-standard-8
        - --env-file=jobs/env/ci-kubernetes-e2e-scalability-common.env
        - --env-file=jobs/env/ci-kubernetes-e2e-scalability-highspeed-common.env
        - --extract=local
        - --gcp-nodes=2000
        - --gcp-project=k8s-scale-testing
        - --gcp-zone=us-east1-a
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-e2e-gce-large-performance
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --minStartupPods=8 --gather-resource-usage=master --gather-metrics-at-teardown=master
        - --timeout=540m
        - --use-logexporter
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-kubemark-e2e-gce-big
    always_run: true
    skip_report: false
    max_concurrency: 12
    skip_branches:
    - release-1.10  # per-release image
    - release-1.9  # per-release image
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=120"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/ci-kubernetes-e2e-kubemark-common.env
        - --env-file=jobs/env/ci-kubernetes-kubemark-gce-big.env
        - --extract=local
        - --gcp-master-size=n1-standard-4
        - --gcp-node-size=n1-standard-8
        - --gcp-nodes=7
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --kubemark
        - --kubemark-nodes=500
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-big
        - --tear-down-previous
        - --test=false
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true
        - --timeout=100m
        # TODO(krzyzacy): Figure out bazel built kubemark image
        #env:
        # - name: KUBEMARK_BAZEL_BUILD
        # value: "y"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-kubemark-e2e-gce-big
    always_run: true
    skip_report: false
    max_concurrency: 12
    branches:
    - release-1.10  # per-release image
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.10
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=120"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/ci-kubernetes-e2e-kubemark-common.env
        - --env-file=jobs/env/ci-kubernetes-kubemark-gce-big.env
        - --extract=local
        - --gcp-master-size=n1-standard-4
        - --gcp-node-size=n1-standard-8
        - --gcp-nodes=7
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --kubemark
        - --kubemark-nodes=500
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-big
        - --tear-down-previous
        - --test=false
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true
        - --timeout=100m
        # TODO(krzyzacy): Figure out bazel built kubemark image
        #env:
        # - name: KUBEMARK_BAZEL_BUILD
        # value: "y"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-kubemark-e2e-gce-big
    always_run: true
    skip_report: false
    max_concurrency: 12
    branches:
    - release-1.9  # per-release image
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.9
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=120"
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --env-file=jobs/env/ci-kubernetes-e2e-kubemark-common.env
        - --env-file=jobs/env/ci-kubernetes-kubemark-gce-big.env
        - --extract=local
        - --gcp-master-size=n1-standard-4
        - --gcp-node-size=n1-standard-8
        - --gcp-nodes=7
        - --gcp-project=k8s-presubmit-scale
        - --gcp-zone=us-east1-b
        - --kubemark
        - --kubemark-nodes=500
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-big
        - --tear-down-previous
        - --test=false
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true
        - --timeout=100m
        # TODO(krzyzacy): Figure out bazel built kubemark image
        #env:
        # - name: KUBEMARK_BAZEL_BUILD
        # value: "y"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"

  - name: pull-kubernetes-kubemark-e2e-gce-scale
    always_run: false
    max_concurrency: 1
    branches:
    - master
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        args:
        - --root=/go/src
        - "--job=$(JOB_NAME)"
        - "--repo=k8s.io/$(REPO_NAME)=$(PULL_REFS)"
        - "--repo=k8s.io/release"
        - "--service-account=/etc/service-account/service-account.json"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - "--timeout=1220"
        - --scenario=kubernetes_e2e
        - --
        - --build
        - --cluster=
        - --env-file=jobs/env/ci-kubernetes-e2e-kubemark-common.env
        - --env-file=jobs/env/ci-kubernetes-kubemark-gce-scale.env
        - --extract=local
        - --gcp-node-size=n1-standard-8
        - --gcp-nodes=82
        - --gcp-project=k8s-scale-testing
        - --gcp-zone=us-east1-b
        - --kubemark
        - --kubemark-nodes=5000
        - --provider=gce
        - --stage=gs://kubernetes-release-pull/ci/pull-kubernetes-kubemark-e2e-gce-scale
        - --test=false
        - --test_args=--ginkgo.focus=\[Feature:Performance\] --gather-resource-usage=true --gather-metrics-at-teardown=true
        - --timeout=1200m
        # TODO(krzyzacy): Figure out bazel built kubemark image
        #env:
        # - name: KUBEMARK_BAZEL_BUILD
        # value: "y"
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        resources:
          requests:
            memory: "6Gi"
