periodics:
- interval: 6h
  name: ci-kubernetes-gce-conformance
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-latest-1-9
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest-1.9
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-latest-1-10
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest-1.10
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-latest-1-11
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest-1.11
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-latest-1-12
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=ci/latest-1.12
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-9
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.9
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-10
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.10
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 6h
  name: ci-kubernetes-gce-conformance-stable-1-11
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=220
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --extract=release/stable-1.11
      - --gcp-master-image=gci
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --provider=gce
      - --test_args=--ginkgo.focus=\[Conformance\] --ginkgo.skip=Alpha|Kubectl|\[(Disruptive|Feature:[^\]]+|Flaky)\]
      - --timeout=200m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
