presubmits:
  kubernetes/kubernetes:
  - name: pull-kubernetes-e2e-gke
    always_run: false
    run_if_changed: '^(cluster/gce|cluster/addons).*$'
    # TODO(bentheelder): enforce this pattern (skip all releases) or implement
    # something better like https://github.com/kubernetes/test-infra/pull/4918
    skip_branches:
    - release-1.10 # per-release image
    - release-1.9 # per-release image
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=90
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --deployment=gke
        - --extract=local
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-project=k8s-jkns-pr-gci-gke
        - --gcp-zone=us-central1-f
        - --ginkgo-parallel=30
        - --gke-create-command=container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard
        - --gke-environment=test
        - '--gke-shape={"default":{"Nodes":4,"MachineType":"n1-standard-2"}}'
        - --provider=gke
        - --stage=gs://kubernetes-release-dev/ci
        - --stage-suffix=pull-kubernetes-e2e-gke
        - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
        - --timeout=65m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gke
    always_run: false
    run_if_changed: '^(cluster/gce|cluster/addons).*$'
    branches:
    - release-1.10 # per-release image
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=90
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --deployment=gke
        - --extract=local
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-project=k8s-jkns-pr-gci-gke
        - --gcp-zone=us-central1-f
        - --ginkgo-parallel=30
        - --gke-create-command=container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard
        - --gke-environment=test
        - '--gke-shape={"default":{"Nodes":4,"MachineType":"n1-standard-2"}}'
        - --provider=gke
        - --stage=gs://kubernetes-release-dev/ci
        - --stage-suffix=pull-kubernetes-e2e-gke
        - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
        - --timeout=65m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.10
        resources:
          requests:
            memory: "6Gi"
  - name: pull-kubernetes-e2e-gke
    always_run: false
    run_if_changed: '^(cluster/gce|cluster/addons).*$'
    branches:
    - release-1.9 # per-release image
    labels:
      preset-service-account: "true"
      preset-k8s-ssh: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - args:
        - --root=/go/src
        - --repo=k8s.io/kubernetes=$(PULL_REFS)
        - --repo=k8s.io/release
        - --upload=gs://kubernetes-jenkins/pr-logs
        - --timeout=90
        - --scenario=kubernetes_e2e
        - --
        - --build=bazel
        - --cluster=
        - --deployment=gke
        - --extract=local
        - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
        - --gcp-node-image=gci
        - --gcp-project=k8s-jkns-pr-gci-gke
        - --gcp-zone=us-central1-f
        - --ginkgo-parallel=30
        - --gke-create-command=container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard
        - --gke-environment=test
        - '--gke-shape={"default":{"Nodes":4,"MachineType":"n1-standard-2"}}'
        - --provider=gke
        - --stage=gs://kubernetes-release-dev/ci
        - --stage-suffix=pull-kubernetes-e2e-gke
        - --test_args=--ginkgo.flakeAttempts=2 --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
        - --timeout=65m
        # Bazel needs privileged mode in order to sandbox builds.
        securityContext:
          privileged: true
        image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-1.9
        resources:
          requests:
            memory: "6Gi"

periodics:
- interval: 30m
  name: ci-kubernetes-e2e-gci-gke
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-create-command=container clusters create --quiet --addons=HttpLoadBalancing,HorizontalPodAutoscaling,KubernetesDashboard
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=50m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-alpha-features
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=200
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --gke-create-command=container clusters create --quiet --enable-kubernetes-alpha
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:(DynamicKubeletConfig|BlockVolume)\]|Networking --ginkgo.skip=Networking-Performance|IPv6|Feature:Volumes --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-alpha-enabled-default
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=200
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-create-command=container clusters create --quiet --enable-kubernetes-alpha
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-flaky
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=320
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Flaky\] --ginkgo.skip=\[Feature:.+\] --minStartupPods=8
      - --timeout=300m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-multizone
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=test
      - --gke-node-locations=us-central1-f,us-central1-a,us-central1-b
      - --provider=gke
      - --test_args=--gce-multizone=true --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-reboot
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=200
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Feature:Reboot\] --minStartupPods=8
      - --timeout=180m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-serial
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-slow
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[Slow\] --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 30m
  name: ci-kubernetes-e2e-gci-gke-updown
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=50
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.focus=\[k8s.io\]\sNetworking.*\[Conformance\] --minStartupPods=8
      - --timeout=30m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 1h
  name: ci-kubernetes-e2e-gke-regional
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=k8s-jkns-e2e-regional
      - --gcp-region=us-central1
      - --ginkgo-parallel
      - --gke-environment=test
      - --provider=gke
      - --test_args=--gce-multizone=true --gce-multimaster=true --ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 1h
  name: ci-kubernetes-e2e-gke-regional-serial
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=520
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-region=us-central1
      - --gke-environment=test
      - --provider=gke
      - --test_args=--gce-multizone=true --gce-multimaster=true --ginkgo.focus=\[Serial\]|\[Disruptive\] --ginkgo.skip=\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=500m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 1h
  name: ci-kubernetes-e2e-gke-regional-slow
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=170
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-region=us-central1
      - --ginkgo-parallel
      - --gke-environment=test
      - --provider=gke
      - --test_args=--gce-multizone=true --gce-multimaster=true --ginkgo.focus=\[Slow\] --ginkgo.skip=\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=150m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 1h
  name: ci-kubernetes-e2e-gke-gci-ci-master
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=70
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --deployment=gke
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-zone=us-central1-f
      - --ginkgo-parallel
      - --gke-environment=test
      - --provider=gke
      - --test_args=--ginkgo.skip=\[Slow\]|\[Serial\]|\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --minStartupPods=8
      - --timeout=50m
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 12h
  name: ci-kubernetes-soak-gke-gci
  labels:
    preset-service-account: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - args:
      - --timeout=820
      - --bare
      - --scenario=kubernetes_e2e
      - --
      - --check-version-skew=false
      - --deployment=gke
      - --down=false
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project=k8s-jkns-gke-gci-soak
      - --gcp-zone=us-central1-f
      - --gke-environment=test
      - --provider=gke
      - --save=gs://kubernetes-jenkins/soak/ci-kubernetes-soak-gke-gci
      - --soak
      - --test_args=--ginkgo.skip=\[Disruptive\]|\[Flaky\]|\[Feature:.+\] --clean-start=true --minStartupPods=8
      - --timeout=800m
      - --up=false
      image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master

- interval: 2h
  name: istio-periodic-e2e-gke-addon
  labels:
    preset-istio-service: "true"
    preset-k8s-ssh: "true"
  spec:
    containers:
    - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
      args:
      - --repo=github.com/ostromart/istio=k8s-prow-test
      - --timeout=90
      - --root=/go/src
      - --scenario=kubernetes_e2e
      - --
      - --check-leaked-resources
      - --cluster=
      - --deployment=gke
      - --env=CLOUDSDK_CONTAINER_USE_V1_API=false
      - --env=TAG=0.8.0
      - --extract=ci/latest
      - --gcp-cloud-sdk=gs://cloud-sdk-testing/ci/staging
      - --gcp-node-image=gci
      - --gcp-project-type=istio-project
      - --gcp-zone=us-central1-f
      - --gke-command-group=alpha
      - --gke-create-command=container clusters create --quiet --num-nodes=4 --no-enable-legacy-authorization --addons=Istio --istio-config=auth=NONE
      - --gke-environment=test
      - --provider=gke
      - --test=false
      - --test-cmd=../tests/e2e_istio_preinstalled.sh
      - --test-cmd-args=simple
      - --test-cmd-name=istio-addon
      - --timeout=60m
