presubmits:
  containerd/cri:
  - name: pull-cri-containerd-build
    always_run: true
    skip_branches:
    - v0.1
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-experimental
        args:
        - "--repo=github.com/containerd/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - --scenario=execute
        - --
        - ./test/build.sh
    run_after_success:
    - name: pull-cri-containerd-node-e2e
      branches:
      - master
      always_run: true
      skip_report: false
      max_concurrency: 8
      labels:
        preset-service-account: "true"
        preset-k8s-ssh: "true"
      spec:
        containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
          args:
          - --root=/go/src
          - "--job=$(JOB_NAME)"
          - "--repo=k8s.io/kubernetes"
          - "--repo=github.com/containerd/$(REPO_NAME)=$(PULL_REFS)"
          - "--service-account=/etc/service-account/service-account.json"
          - "--upload=gs://kubernetes-jenkins/pr-logs"
          - "--timeout=90"
          - --scenario=kubernetes_e2e
          - --
          - --deployment=node
          - --gcp-project=cri-c8d-pr-node-e2e
          - --gcp-zone=us-central1-f
          - '--node-test-args=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --flakeAttempts=2
          - --timeout=65m
          - "--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/cri-master/image-config.yaml -node-env=PULL_REFS=$(PULL_REFS)"

    - name: pull-cri-containerd-node-e2e
      branches:
      - release/1.0
      always_run: true
      skip_report: false
      max_concurrency: 8
      labels:
        preset-service-account: "true"
        preset-k8s-ssh: "true"
      spec:
        containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-master
          args:
          - --root=/go/src
          - "--job=$(JOB_NAME)"
          - "--repo=k8s.io/kubernetes=release-1.10"
          - "--repo=github.com/containerd/$(REPO_NAME)=$(PULL_REFS)"
          - "--service-account=/etc/service-account/service-account.json"
          - "--upload=gs://kubernetes-jenkins/pr-logs"
          - "--timeout=90"
          - --scenario=kubernetes_e2e
          - --
          - --deployment=node
          - --gcp-project=cri-c8d-pr-node-e2e
          - --gcp-zone=us-central1-f
          - '--node-test-args=--container-runtime=remote --container-runtime-endpoint=unix:///run/containerd/containerd.sock --container-runtime-process-name=/home/containerd/usr/local/bin/containerd --container-runtime-pid-file= --kubelet-flags="--cgroups-per-qos=true --cgroup-root=/ --runtime-cgroups=/system.slice/containerd.service" --extra-log="{\"name\": \"containerd.log\", \"journalctl\": [\"-u\", \"containerd\"]}"'
          - --node-tests=true
          - --provider=gce
          - --test_args=--nodes=8 --focus="\[NodeConformance\]" --skip="\[Flaky\]|\[Slow\]|\[Serial\]" --flakeAttempts=2
          - --timeout=65m
          - "--node-args=--image-config-file=/workspace/test-infra/jobs/e2e_node/containerd/cri-master/image-config.yaml -node-env=PULL_REFS=$(PULL_REFS)"

  - name: pull-cri-containerd-verify
    always_run: true
    skip_branches:
    - v0.1
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20180829-29e661965-experimental
        args:
        - "--repo=github.com/containerd/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://kubernetes-jenkins/pr-logs"
        - --scenario=execute
        - --
        - ./test/verify.sh
